\version "2.24.0"

%% Corpus-wide library: articulation marks, songbookBeatMarks. A real file
%% under songs/, mirrored into the sandbox, so this include resolves both when
%% the build compiles the sandbox copy and when the editor compiles the source.
\include "../../songbook.ily"

%% macros.ly carries only `songtempo = <song.yml info.tempo>`, generated by
%% band-songbook next to the .ly. It is missing when a file is compiled
%% straight from songs/ in the editor, hence the guard and the fallback tempo
%% (editor-only: a build always uses the real tempo from song.yml).
#(if (ly:find-file "macros.ly")
     (ly:parser-include-string "\\include \"macros.ly\"")
     (ly:parser-define! 'songtempo 100))

%% Shared definitions only - no \header and no \score, so this file can be
%% included without adding pages or a second midi file to the build.

songTempo = { \tempo 4 = \songtempo }

%% Capo on fret 4: raise every open string by a major third, so the tab shows
%% frets counted from the capo while the notes keep their sounding pitch.
capoTuning = #(map (lambda (p) (ly:pitch-transpose p (ly:make-pitch 0 2 0))) guitar-tuning)

%% Show note durations in the tablature. A TabStaff hides stems, flags, beams
%% and dots by default; this is the rhythm-related subset of \tabFullNotation,
%% without the time signature, dynamics and tuplet brackets it also restores.
tabDurations = {
  \revert TabStaff.Stem.length
  \revert TabStaff.Stem.no-stem-extend
  \revert TabStaff.Stem.details
  \revert TabStaff.Stem.stencil
  \revert TabStaff.Flag.style
  \revert TabStaff.Flag.stencil
  \override TabStaff.Stem.stencil = #tabvoice::draw-double-stem-for-half-notes
  \override TabStaff.Stem.X-extent = #tabvoice::make-double-stem-width-for-half-notes
  \revert TabStaff.NoteColumn.ignore-collision
  \set TabStaff.autoBeaming = ##t
  \revert TabStaff.Beam.stencil
  \revert TabStaff.Dots.stencil
  \revert TabStaff.Tie.stencil
  \revert TabStaff.Tie.after-line-breaking
  \revert TabStaff.Rest.stencil
  \revert TabStaff.MultiMeasureRest.stencil
  \revert TabStaff.MultiMeasureRestNumber.stencil
  \revert TabStaff.MultiMeasureRestText.stencil
}
